# Generated by Django 2.2.16 on 2020-10-30 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_auto_20201028_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritoCartas', to='api.Carta')),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritoSorteos', to='api.Sorteo')),
            ],
        ),
    ]
