# Generated by Django 2.2.16 on 2020-10-30 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carrito',
            table='carrito',
        ),
    ]
