# Generated by Django 2.2.16 on 2020-11-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0002_auto_20201029_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='nombreCompleto',
            field=models.CharField(blank=True, db_column='nombre_completo', max_length=255, null=True),
        ),
    ]
