# Generated by Django 2.2.16 on 2020-11-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0003_auto_20201104_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='token',
        ),
        migrations.AddField(
            model_name='carrito',
            name='tokenCompra',
            field=models.CharField(blank=True, db_column='token_compra', max_length=100, null=True),
        ),
    ]
