# Generated by Django 2.2.16 on 2020-10-28 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='static/img/')),
            ],
            options={
                'db_table': 'cartas',
            },
        ),
        migrations.CreateModel(
            name='Sorteos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('detalles', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fechaHoraSorteo', models.DateTimeField(db_column='fecha_hora_sorteo')),
            ],
            options={
                'db_table': 'sorteos',
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='static/img/')),
                ('principal', models.BooleanField(default=False)),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='api.Sorteos')),
            ],
            options={
                'db_table': 'imagenes',
            },
        ),
    ]
