# Generated by Django 2.2.16 on 2020-10-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartas',
            new_name='Carta',
        ),
        migrations.RenameModel(
            old_name='Imagenes',
            new_name='Imagen',
        ),
        migrations.RenameModel(
            old_name='Sorteos',
            new_name='Sorteo',
        ),
    ]
