# Generated by Django 2.2.16 on 2020-10-29 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201028_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorteo',
            options={'ordering': ['-fechaHoraSorteo']},
        ),
    ]
