# Generated by Django 2.2.16 on 2020-11-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201028_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='costoBoleto',
            field=models.DecimalField(db_column='costo_boleto', decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
