# Generated by Django 2.2.16 on 2020-11-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sorteo_costoboleto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorteo',
            name='costoBoleto',
        ),
        migrations.AddField(
            model_name='sorteo',
            name='costoCarta',
            field=models.DecimalField(db_column='costo_carta', decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
