# Generated by Django 2.2.16 on 2020-11-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201105_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
