# Generated by Django 2.2.16 on 2020-11-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201105_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
